lidar:
  lidar_topic: /ouster/points
  frame_id: os_sensor

camera:
  image_topic: /image_raw
  projected_topic: /usb_cam/projected_image
  image_size:
    width: 640
    height: 480
  frame_id: camera

chessboard:
  pattern_size:
    rows: 6
    columns: 9
  square_size_meters: 0.03

general:
  config_folder: /home/user1/ros2_fusion_ws/src/ros2_camera_lidar_fusion/config
  data_folder: /home/user1/ros2_fusion_ws/src/ros2_camera_lidar_fusion/data1
  correspondence_file: ros2_camera_lidar_fusion_correspondences.txt
  camera_intrinsic_calibration: camera_intrinsic_calibration.yaml
  camera_extrinsic_calibration: camera_extrinsic_calibration.yaml
  slop: 1.0
  max_file_saved: 10
  keyboard_listener: True
  get_intrinsics: True
  get_extrinsics: True